backend/controllers/ProductController.php
<?php
    namespace backend\controllers;

    use backend\models\Attribute;
    use Yii;
    use common\models\Category;
    use common\models\Discount;
    use backend\models\GridViewConfig;
    use common\models\Product;
    use backend\searches\Product as ProductSearch;
    use yii\data\ActiveDataProvider;
    use yii\web\NotFoundHttpException;
    use yii\web\UploadedFile;
    use backend\forms\Attributes as AttributesForm;
    use backend\forms\Product as ProductForm;
    use backend\forms\ProductImport as ProductImportForm;
    use common\models\ProductAttribute;
    use common\models\ProductReview;
    use common\models\ProductSellCross;
    use common\models\ProductSellUp;

    class ProductController extends BaseController
    {
        public function actionIndex()
        {
            $searchModel = new ProductSearch();
            $gridViewColumns = GridViewConfig::prepareData(Product::className());
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'gridViewColumns' => $gridViewColumns,
            ]);
        }

        public function actionView($id)
        {
            $attributes = new ActiveDataProvider([
                'query' => ProductAttribute::find()->where(['product_id' => $id])
            ]);
            $crossSells = new ActiveDataProvider([
                'query' => ProductSellCross::find()->where(['product_id' => $id])
            ]);
            $upSells = new ActiveDataProvider([
                'query' => ProductSellUp::find()->where(['product_id' => $id])
            ]);
            $reviews = new ActiveDataProvider([
                'query' => ProductReview::find()->where(['product_id' => $id])
            ]);

            return $this->render('view', [
                'model' => $this->findModel($id),
                'attributes' => $attributes,
                'crossSell' => $crossSells,
                'upSell' => $upSells,
                'reviews' => $reviews,
            ]);
        }
        public function actionCreate()
        {
            $model = new Product();
            $productsForm = new ProductForm();
            $categories = Category::prepareForForm();
            $discounts = Discount::prepareForForm();
            $attributes = Attribute::getAllWithoutUsed(null, true);

            if ($model->load(Yii::$app->request->post())) {
                if ($model->save()) {
                    return $this->redirectWithMessage(['view', 'id' => $model->id],
                        Yii::t("system", "Object was created successfully."));
                }
                else{
                    return $this->redirectWithMessage(['view', 'id' => $model->id],
                        Yii::t("system", "An unexpected error occurred, please contact with administrator."), "error");
                }
            }
            else {
                return $this->render('create', [
                    'model' => $model,
                    'attributes' => $attributes,
                    'categories' => $categories,
                    'discounts' => $discounts,
                    'productsForm' => $productsForm,
                ]);
            }
        }
        public function actionUpdate($id)
        {
            $model = $this->findModel($id);
            $productsForm = new ProductForm();
            $categories = Category::prepareForForm();
            $discounts = Discount::prepareForForm();
            $attributes = Attribute::getAllWithoutUsed($model->id, true);

            if ($model->load(Yii::$app->request->post())) {
                if ($model->save()) {
                    return $this->redirectWithMessage(['view', 'id' => $model->id],
                        Yii::t("system", "Object was created successfully."));
                }
                else{
                    return $this->redirectWithMessage(['view', 'id' => $model->id],
                        Yii::t("system", "An unexpected error occurred, please contact with administrator."), "error");
                }
            }
            else {
                return $this->render('update', [
                    'model' => $model,
                    'attributes' => $attributes,
                    'categories' => $categories,
                    'discounts' => $discounts,
                    'productsForm' => $productsForm,
                ]);
            }
        }
        public function actionClone($id)
        {
            /** @var Product $model */
            /** @var Product $clonedModel */
            $model = $this->findModel($id);
            $clonedModel = $model->cloneProduct();

            if($clonedModel){
                return $this->redirect(['product/update', 'id' => $clonedModel->id]);
            }
            else{
                return $this->redirect(['product/index']);
            }
        }
        public function actionDelete($id)
        {
            $model = $this->findModel($id);
            $model->deleted = 1;
            $model->save();

            return $this->redirect(['index']);
        }
        public function actionDeleteSelected($ids)
        {
            /** @var Product[] $models */
            $models = Product::find()->where(['id' => explode(",", $ids)])->all();

            foreach($models AS $model){
                $model->deleted = 1;
                $model->save();
            }

            return $this->redirect(['index']);
        }
        public function actionImport()
        {
            $form = new ProductImportForm();

            if(Yii::$app->request->isPost){
                $form->jsonFile = UploadedFile::getInstance($form, 'jsonFile');
                $form->xmlFile = UploadedFile::getInstance($form, 'xmlFile');

                if($form->import()){
                    return $this->redirect(['index']);
                }
            }

            return $this->render("import", [
                'model' => $form
            ]);
        }

        public function actionCrossSellDelete($id)
        {
            $model = ProductSellCross::findOne($id);

            if ($model) {
                $model->delete();
            }

            return $this->redirect(Yii::$app->request->referrer);
        }


        public function actionUpSellDelete($id)
        {
            $model = ProductSellUp::findOne($id);

            if ($model) {
                $model->delete();
            }

            return $this->redirect(Yii::$app->request->referrer);
        }

        protected function findModel($id)
        {
            /** @var Product $model */
            if (($model = Product::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
    }

frontend/controllers/ProductController.php
<?php
    namespace frontend\controllers;

    use common\services\Alerts\SuccessAlert;
    use Yii;
    use common\models\Favorite;
    use common\models\ProductOfADay;
    use common\models\Product;
    use frontend\forms\ProductReview as ProductReviewForm;
    use yii\helpers\Url;
    use yii\web\NotFoundHttpException;
    use frontend\forms\BuyProduct;

    class ProductController extends BaseController
    {
        /**
         * @param string $url
         * @param int $id
         * @return string
         * @throws NotFoundHttpException
         */
        public function actionDetail($url, $id)
        {
            /** @var Product $product */
            $product = Product::find()->where(['id' => $id, 'processed_name' => $url, 'type' => Product::TYPE_STANDARD])->one();

            if ($product) {
                Yii::$app->manageBarService->addAction(Yii::t("site", "Edit product"),
                    Yii::$app->urlManagerBackend->createUrl(['product/update', 'id' => $product->id])
                );

                $this->setBreadCrumbs($product);
                $this->setTitle($product->name);

                return $this->render('detail', [
                    'isSpecial' => false,
                    'product' => $product,
                    'reviewForm' => new ProductReviewForm(),
                    'buyForm' => new BuyProduct(),
                ]);
            } else {
                throw new NotFoundHttpException("Product does not exists.");
            }
        }

        /**
         * @param int $id
         * @return string
         * @throws NotFoundHttpException
         */
        public function actionDetailSpecial($id)
        {
            /** @var ProductOfADay $productOfADay */
            $productOfADay = ProductOfADay::find()->where(['id' => $id])->one();

            if ($productOfADay->product) {
                Yii::$app->manageBarService->addAction(Yii::t("product", "Edit product"),
                    Yii::$app->urlManagerBackend->createUrl(['product/update', 'id' => $productOfADay->product->id])
                );
                Yii::$app->manageBarService->addAction(Yii::t("product", "Edit product of a day"),
                    Yii::$app->urlManagerBackend->createUrl(['product-of-a-day/update', 'id' => $productOfADay->id])
                );

                $this->setBreadCrumbs($productOfADay->product, true);
                $this->setTitle($productOfADay->product->name);

                return $this->render('detail-special', [
                    'isSpecial' => true,
                    'productOfADay' => $productOfADay,
                    'product' => $productOfADay->product,
                    'buyForm' => new BuyProduct()
                ]);
            } else {
                throw new NotFoundHttpException("Product does not exists.");
            }
        }

        public function actionSaveReview()
        {
            if (Yii::$app->request->isPost && !Yii::$app->user->isGuest) {
                $form = new ProductReviewForm();

                if ($form->load(Yii::$app->request->post()) && $form->saveReview()) {
                    $product = Product::findOne($form->product_id);

                    Yii::$app->alertsService->addAlert(new SuccessAlert(Yii::t("product", "Review was saved and it is waiting for acceptance.")));

                    return $this->redirect(['product/detail', 'id' => $product->id, 'url' => $product->processed_name]);
                }
            }

            return $this->redirect(['site/index']);
        }

        /**
         * @param int $id
         * @return \yii\web\Response
         */
        public function actionAddToFavorites($id)
        {
            if (!Yii::$app->user->isGuest) {
                $favorite = new Favorite();

                $favorite->product_id = $id;

                if ($favorite->save()) {
                    Yii::$app->alertsService->addAlert(new SuccessAlert(Yii::t("product", "Product was saved to favorites list")));
                }
            }

            return $this->redirect(Yii::$app->request->referrer);
        }

        /**
         * @param Product $product
         * @param bool $special
         */
        private function setBreadCrumbs(Product $product, $special = false)
        {
            if (Yii::$app->layoutService->hasBreadcrumbs()) {
                if ($special === false) {
                    $category = $product->category;

                    while (!is_null($category)) {
                        Yii::$app->layoutService->getBreadcrumbs()->addLink($category->name,
                            Url::toRoute(['category/index', 'url' => $category->url, 'id' => $category->id])
                        );

                        $category = $category->parent;
                    }

                    Yii::$app->layoutService->getBreadcrumbs()->reverseData();
                } else {
                    Yii::$app->layoutService->getBreadcrumbs()->addLabel(Yii::t("product", "Product of a day"));
                }

                Yii::$app->layoutService->getBreadcrumbs()->addLabel($product->name);
            }
        }
    }

backend/views/product/view/attributes.php
<?php
    use kartik\grid\GridView;
    use yii\helpers\Url;

    /** @var \yii\data\ActiveDataProvider $data */
?>

<?= GridView::widget([
    'dataProvider' => $data,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        'productAttribute.name',
        'option.name',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}',
            'buttons' => [
                'delete' => function ($url, $model) {
                    return '<a href="' . Url::toRoute(['product-attribute/delete', 'id' => $model->id]) . '" data-pjax="no"><span class="glyphicon glyphicon-trash"></span></a>';
                },
            ]
        ]
    ],
    'layout' => "{items}\n{pager}",
    'responsive' => true,
    'export' => false,
]) ?>

backend/views/product/view/crossSell.php
<?php
    use kartik\grid\GridView;
    use yii\helpers\Url;

    /** @var \yii\data\ActiveDataProvider $data*/
?>

<?= GridView::widget([
    'dataProvider' => $data,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        'product.name',
        'product.cost',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}',
            'buttons' => [
                'delete' => function ($url, $model) {
                    return '<a href="' . Url::toRoute(['product/cross-sell-delete', 'id' => $model->id]) . '" data-pjax="no"><span class="glyphicon glyphicon-trash"></span></a>';
                },
            ]
        ]
    ],
    'layout' => "{items}\n{pager}",
    'responsive' => true,
    'export' => false,
]) ?>

backend/views/product/view/general.php
<?php
    use yii\widgets\DetailView;
?>
<?= DetailView::widget([
    'model' => $data,
    'attributes' => [
        'id',
        'name',
        [
            'attribute' => 'description',
            'format' => 'html'
        ],
        [
            'attribute' => 'additional_field',
            'format' => 'html'
        ],
        'category.name',
        'discount.name',
        'previous_cost',
        'cost',
        'costAfterDiscount',
        'quantity',
        'available',
        'code',
        'bought_count',
        'modified_date',
        'created_date',
    ],
]) ?>

backend/views/product/view/images.php
<?php
    /** @var \common\models\Product $data */
?>
<div class="images row" id="productImages">
    <?php if (!empty($data->images)): ?>
        <?php foreach ($data->images AS $image): ?>
            <?php
                if ($data->mainImage && $data->mainImage->id == $image->id) {
                    $class = "mainImage";
                } else {
                    $class = "";
                }
            ?>
            <div class="imageWrap col-lg-2 col-md-3 col-sm-6 col-xs-12 <?= $class; ?>">
                <div class="innerWrapper">
                    <i class="fa fa-star icon" aria-hidden="true"></i>
                    <div class="image">
                        <img src="<?= $image->path; ?>" alt="<?= $image->name; ?>" data-id="<?= $image->id; ?>" class="img-responsive">
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="emptyBlock col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <i class="fa fa-frown-o icon" aria-hidden="true"></i>
            <span class="text"><?= Yii::t("product", "There are no images to display."); ?></span>
        </div>
    <?php endif; ?>
</div>

backend/views/product/view/reviews.php
<?php
    use kartik\grid\GridView;
    use yii\helpers\Url;

    /** @var \yii\data\ActiveDataProvider $data */
?>

<?= GridView::widget([
    'dataProvider' => $data,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        [
            'attribute' => 'rating',
            'value' => function ($model) use ($data) {
                $rating = $model->rating;
                $response = "";

                while ($rating-- > 0) {
                    $response .= "<i class='fa fa-star'></i>";
                }

                return $response;
            },
            'format' => 'html',
        ],
        'text',
        'accepted_text',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete} {accept}',
            'buttons' => [
                'delete' => function ($url, $model) {
                    return '<a href="' . Url::toRoute(['product-review/delete', 'id' => $model->id]) . '" data-pjax="no"><span class="glyphicon glyphicon-trash"></span></a>';
                },
                'accept' => function ($url, $model) {
                    if (!$model->accepted) {
                        return '<a href="' . Url::toRoute(['product-review/accept', 'id' => $model->id]) . '" data-pjax="no"><span class="glyphicon glyphicon-ok"></span></a>';
                    }
                }
            ]
        ]
    ],
    'layout' => "{items}\n{pager}",
    'responsive' => true,
    'export' => false,
]) ?>

backend/views/product/view/upSell.php
<?php
    use kartik\grid\GridView;
    use yii\helpers\Url;

    /** @var \yii\data\ActiveDataProvider $data */
?>

<?= GridView::widget([
    'dataProvider' => $data,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        'product.name',
        'cost',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}',
            'buttons' => [
                'delete' => function ($url, $model) {
                    return '<a href="' . Url::toRoute(['product/up-sell-delete', 'id' => $model->id]) . '" data-pjax="no"><span class="glyphicon glyphicon-trash"></span></a>';
                },
            ]
        ]
    ],
    'layout' => "{items}\n{pager}",
    'responsive' => true,
    'export' => false,
]) ?>