common/models/Language.php
<?php
    namespace common\models;

    use Yii;
    use yii\db\ActiveRecord;
    use yii\helpers\ArrayHelper;
    use backend\models\LanguageSource as LanguageSourceBackend;
    use frontend\models\LanguageSource as LanguageSourceFrontend;

    /**
     * This is the model class for table "{{%i18n}}".
     *
     * @property integer $id
     * @property string $name
     * @property string $symbol
     * @property string $module
     */
    class Language extends ActiveRecord
    {
        protected $newLanguage;

        public static function tableName()
        {
            return '{{%i18n}}';
        }

        public function rules()
        {
            return [
                [['name', 'symbol'], 'string'],
                [['name'], 'string', 'max' => 64],
                [['symbol'], 'string', 'max' => 10],
                [['module'], 'string', 'max' => 64],
            ];
        }
        public function attributeLabels()
        {
            return [
                'id' => Yii::t('language', 'ID'),
                'name' => Yii::t('language', 'Name'),
                'symbol' => Yii::t('language', 'Symbol'),
                'module' => Yii::t('language', 'Module'),
            ];
        }

        public function save($runValidation = true, $attributeNames = null)
        {
            $this->newLanguage = $this->getIsNewRecord();

            return parent::save($runValidation, $attributeNames);
        }
        public function afterSave($insert, $changedAttributes)
        {
            if($this->newLanguage){
                switch($this->module){
                    case "frontend":
                        $sources = LanguageSourceFrontend::find()->all();
                        break;

                    case "backend":
                    default:
                        $sources = LanguageSourceBackend::find()->all();
                        break;
                }

                /** @var LanguageSourceFrontend | LanguageSourceBackend $source */
                foreach($sources AS $source){
                    $message = new LanguageMessage();

                    $message->i18n_id = $this->id;
                    $message->source_id = $source->id;
                    $message->translation = $source->message;

                    $message->save();
                }
            }

            parent::afterSave($insert, $changedAttributes);
        }

        public function delete()
        {
            LanguageMessage::deleteAll(['i18n_id' => $this->id]);

            return parent::delete();
        }

        public static function groupByCategories($module = "backend")
        {
            switch($module){
                case "frontend":
                    $sources = LanguageSourceFrontend::find()->all();
                    break;

                case "backend":
                default:
                    $sources = LanguageSourceBackend::find()->all();
                    break;
            }

            $result = [];

            /** @var LanguageSourceFrontend | LanguageSourceBackend $source */
            foreach($sources AS $source){
                $translations = LanguageMessage::find()->where(['source_id' => $source->id])->all();

                /** @var LanguageMessage $translation */
                foreach($translations AS $translation){
                    $result[$source->category][$source->message][$translation->i18n_id] = $translation->translation;
                }
            }

            return $result;
        }
        public static function prepareForManage($id)
        {
            $language = Language::findOne($id);
            $data = [];

            switch($language->module){
                case "frontend":
                    $sources = LanguageSourceFrontend::find()->orderBy('category')->all();
                    break;
                case "backend":
                default:
                    $sources = LanguageSourceBackend::find()->orderBy('category')->all();
                    break;
            }


            /** @var LanguageSourceFrontend | LanguageSourceBackend $source */
            foreach($sources AS $source){
                /** @var LanguageMessage $message */
                $message = LanguageMessage::find()->where(['i18n_id' => $language->id, 'source_id' => $source->id])->one();

                if($message){
                    $data[$source->category][] = [
                        'id' => $source->id,
                        'source' => $source->message,
                        'message' => $message->translation,
                    ];
                }
                else{
                    $data[$source->category][] = [
                        'id' => $source->id,
                        'source' => $source->message,
                        'message' => $source->message,
                    ];
                }
            }

            return $data;
        }
        public static function prepareForForm($module = "backend")
        {
            return ArrayHelper::map(self::find()->where(['module' => $module])->all(), 'symbol', 'name');
        }
        public static function saveMessages($id)
        {
            $data = Yii::$app->request->post();
            $transaction = LanguageMessage::getDb()->beginTransaction();

            try{
                foreach($data AS $key => $value){
                    if((int) $key){
                        /** @var LanguageMessage $message */
                        $message = LanguageMessage::find()->where(['source_id' => $key, 'i18n_id' => $id])->one();

                        if($message){
                            $message->translation = $value;
                            $message->save();
                        }
                    }
                }

                $transaction->commit();

                return true;
            }
            catch(\Exception $ex){
                $transaction->rollBack();
            }

            return false;
        }
        public static function existsForModule($module, $symbol)
        {
            return Language::find()->where(['module' => $module, 'symbol' => $symbol])->one();
        }
    }

backend/controllers/LanguageController.php
<?php
    namespace backend\controllers;

    use Yii;
    use yii\data\ActiveDataProvider;
    use yii\web\NotFoundHttpException;
    use common\models\Language;

    class LanguageController extends BaseController
    {
        public function actionIndex($module)
        {
            $dataProvider = new ActiveDataProvider([
                'query' => Language::find()->where(['module' => $module])
            ]);

            return $this->render('index', [
                'dataProvider' => $dataProvider
            ]);
        }

        public function actionCreate()
        {
            /** @var Language $model */
            $model = new Language();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['index', 'module' => $model->module]);
            }

            return $this->render('create', [
                'model' => $model
            ]);
        }
        public function actionUpdate($id)
        {
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['index', 'module' => $model->module]);
            }

            return $this->render('update', [
                'model' => $model
            ]);
        }
        public function actionManage($id)
        {
            $language = Language::findOne($id);

            if(Yii::$app->request->isPost && Language::saveMessages($id)) {
                return $this->redirect(['index', 'module' => $language->module]);
            }
            else{
                return $this->render('manage', [
                    'data' => Language::prepareForManage($id),
                ]);
            }
        }
        public function actionDelete($id)
        {
            $model = $this->findModel($id);

            if($model->delete()){
                return $this->redirect(['index', 'module' => $model->module]);
            }
            else{
                return $this->redirect(['index', 'module' => $model->module]);
            }
        }
        protected function findModel($id){
            /** @var Language $model */
            if (($model = Language::findOne($id)) !== null) {
                return $model;
            }
            else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
    }

backend/views/language/_form.php
<?php
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>

<?php $form = ActiveForm::begin(['id' => 'language-form']); ?>
    <?= $form->field($model, 'name') ?>
    <div class="form-group">
        <div class="form-message form-message-primary">
            <?= Yii::t("language", "For consistency, all locale IDs should be canonicalized to the format of eg. en-US or pl-PL"); ?>
        </div>
    </div>
    <?= $form->field($model, 'symbol') ?>
    <?= $form->field($model, 'module')->dropDownList([
            'frontend' => Yii::t("language", "Frontend"),
            'backend' => Yii::t("language", "Backend"),
        ],[
        'prompt' => Yii::t("language", "Choose module")
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t("system", "Create") : Yii::t("system", "Update"), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
<?php ActiveForm::end(); ?>

backend/views/language/create.php
<?php
    $this->title = Yii::t("language", "Add language");;
    $this->params['breadcrumbs'][] = ['label' => Yii::t("navigation", "Languages"), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="language-create box box-form">
    <div class="box-content">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

backend/views/language/index.php
<?php
    use common\models\Language;
    use kartik\grid\GridView;
    use kartik\tabs\TabsX;
    use yii\helpers\Url;

    /**
     * @var \yii\data\ActiveDataProvider $dataProvider
     */

    $this->title = Yii::t("navigation", "Languages");
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-content">
        <?= TabsX::widget([
            'enableStickyTabs' => true,
            'items' => [
                [
                    'content' => GridView::widget([
                        'dataProvider' => $dataProvider,
                        'columns' => [
                            'name',
                            'symbol',
                            [
                                'class' => '\kartik\grid\ActionColumn',
                                'template' => '{update}{manage}{delete} ',
                                'buttons' => [
                                    'view' => function () {
                                        return '';
                                    },
                                    'manage' => function ($url, $model) {
                                        /** @var Language $model */
                                        return '<a href="' . Url::toRoute(['language/manage', 'id' => $model->id]) . '" data-pjax="no"><i class="fa fa-braille"></i></a>';
                                    }
                                ]
                            ]
                        ],
                        'responsive' => true,
                        'export' => false,
                        'pjax' => true,
                        'pjaxSettings' => [
                            'neverTimeout' => true,
                        ]
                    ]),
                    'label' => Yii::t("user", "All users")
                ],
                [
                    'label' => Yii::t("language", "Add language"),
                    'linkOptions' => [
                        'data-url' => Url::to(['/language/create']),
                        'class' => 'link link-success'
                    ],
                    'headerOptions' => [
                        'class' => 'link-parent'
                    ]
                ]
            ],
            'position' => TabsX::POS_ABOVE,
            'encodeLabels' => false,
            'fade' => false
        ]); ?>
    </div>
</div>

backend/views/language/manage.php
<?php
    use yii\helpers\Html;

    $this->title = Yii::t("navigation", "Languages");
    $this->params['breadcrumbs'][] = ['label' => Yii::t('navigation', 'Languages'), 'url' => ['index']];
?>
<div class="box language-manage">
    <div class="box-content">
        <?php if(!empty($data)): ?>
            <form method="POST" id="languageForm">
                <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken();?>">

                <?php foreach($data AS $lang => $translations): ?>
                    <section id="category_<?= $lang; ?>" class="row category">
                        <div class="col-lg-12 col-md-12">
                            <h4><?= ucfirst($lang); ?></h4>
                        </div>
                        <?php foreach($translations as $translation): ?>
                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="<?= $translation['id']; ?>"><?= $translation['source']; ?></label>
                                    <div>
                                        <input type="text" id="<?= $translation['id'];?>" name="<?= $translation['id']; ?>" value="<?= $translation['message']; ?>" class="form-control">
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </section>
                <?php endforeach; ?>

                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group" id="updateBtnWrap">
                            <div class="text-center">
                                <?= Html::submitButton(Yii::t('system', 'Update'), ['class' => 'btn btn-primary', 'id' => 'addProductBtn']) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        <?php else: ?>
            <div class="noData">
                <p class="text-center"><?= Yii::t("language", "No translations found");?></p>
            </div>
        <?php endif; ?>
    </div>
</div>

backend/views/language/update.php
<?php
    $this->title = Yii::t("language", "Update language");;
    $this->params['breadcrumbs'][] = ['label' => Yii::t("navigation", "Languages"), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="language-update box box-form">
    <div class="box-content">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>